### ISSUE TITLE
Improve the show/hide password icons

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet-icons#100]
Following the new story added for TextInput to show/hide password field, we will like to publish the best icons option. 
In case the icons for the password use case don't exist yet, we should consider to create them. currently, these are the icons that are being used 
https://storybook.grommet.io/?selectedKind=TextInput&selectedStory=Password%20input&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

`<FormLock  /> : <View />`

**Comment by ShimiSun** [comment]
Hi @JetLim, can you please take a look here and do the design investigation for this issue?

**Comment by JetLim** [comment]
with 'Hide Value' icon.

![preview](https://user-images.githubusercontent.com/16657091/56931447-e9b26f00-6a94-11e9-82e0-054d130e08cb.png)

**Comment by ShimiSun** [comment]
closing, and tracking the story here https://github.com/grommet/grommet/issues/3097
