### ISSUE TITLE
Node.js icon request

### ISSUE THREAD

**Issue by atreb** [grommet/grommet-icons#101]
I use nodejs and docker extensively at my workplace. Was happy to see docker icon but missed nodejs one. Looking forward to getting support for it. Few links which hopefully may help:
https://fontawesome.com/icons?d=gallery&q=nodejs
https://nodejs.org/en/about/resources/

**Comment by L0ZZI** [comment]
Done!

![node](https://user-images.githubusercontent.com/1753301/54230250-48ab2d00-44c3-11e9-9020-6917693c5244.png)
[node.svg.zip](https://github.com/grommet/grommet-icons/files/2958475/node.svg.zip)

**Comment by atreb** [comment]
Thanks @L0ZZI

**Comment by oorestisime** [comment]
Closing this since it was merged.
