### ISSUE TITLE
Add Spotify and SoundCloud icons

### ISSUE THREAD

**Issue by credator** [grommet/grommet-icons#104]
Any chance you can add icons for Spotify and SoundCloud.  Something like the examples below (from icomoon).

![image](https://user-images.githubusercontent.com/47538163/54531247-30239280-495b-11e9-9912-5e3cd83e17e2.png)

I can PR some SVGs if you'd like?

**Comment by ShimiSun** [comment]
@credator yea, go ahead, check out the https://github.com/grommet/grommet-icons/blob/master/CONTRIBUTING.md
@L0ZZI FYI

**Comment by JetLim** [comment]
![soundcloud](https://user-images.githubusercontent.com/16657091/55360207-8c70d100-5488-11e9-89a2-e0f6f396655e.png)

Let us know if the 'SoundCloud' logo is still needed.
It is ready to go.
