### ISSUE TITLE
NPM icon

### ISSUE THREAD

**Issue by oorestisime** [grommet/grommet-icons#105]
I would love an npm icon to be able to add npm links using just that icon.

**Comment by ShimiSun** [comment]
see #101, I need to update the site and release.

**Comment by oorestisime** [comment]
That is nodejs. i am looking for npm. something like http://cdn.onlinewebfonts.com/svg/img_395039.png

**Comment by JetLim** [comment]
![NPM](https://user-images.githubusercontent.com/16657091/55263234-8b903300-522d-11e9-9926-44e4b3c17e0a.png)

Do we need just an 'N', or the complete logotype for NPM?

**Comment by JetLim** [comment]
![n_box](https://user-images.githubusercontent.com/16657091/55746468-99447600-59ee-11e9-9430-c5243f1a32f2.png)

The 'N' is ready. 
@oorestisime @L0ZZI

**Comment by ShimiSun** [comment]
@JetLim, perfect 💯 
can you please send me the SVG?

**Comment by L0ZZI** [comment]
I like the "n" jet!
