### ISSUE TITLE
Spectrum Logo

### ISSUE THREAD

**Issue by ganobrega** [grommet/grommet-icons#115]
![Spectrum](https://user-images.githubusercontent.com/4602864/56528415-85882c00-6525-11e9-95b1-2e9a62f6efac.png)
By: https://github.com/withspectrum/spectrum

Please, add the logo of the **Social Network**: [https://spectrum.chat/](https://spectrum.chat/).

`<path d="M0,3.356c0,-1.767 1.433,-3.2 3.2,-3.2l2.8,0c23.196,0 42,18.804 42,42l0,2.8c0,1.768 -1.433,3.2 -3.2,3.2l-17.6,0c-1.767,0 -3.2,-1.432 -3.2,-3.2l0,-2.8c0,-9.941 -8.059,-18 -18,-18l-2.8,0c-1.767,0 -3.2,-1.432 -3.2,-3.2l0,-17.6Z"></path>`

**Comment by JetLim** [comment]
It would be great if the Spectrum Chat design team can provide a vector with the logo and the type of the company. Else, we have recreated the logo only without the type. 

![spectrumchat](https://user-images.githubusercontent.com/16657091/56996825-a6223880-6b5a-11e9-85e7-327a782ac83a.png)

**Comment by JetLim** [comment]
Minor refinements. The icon is ready. :)

![spectrumchat2](https://user-images.githubusercontent.com/16657091/57002101-b8f43780-6b71-11e9-88ad-765b4a3d3797.png)
