### ISSUE TITLE
Sorting icons by the newest

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet-icons#121]
@L0ZZI it would be great to sort icons.grommet.io by newest...

**Comment by ShimiSun** [comment]
we need to work out how will be the UX for displaying it, my initial thought maybe the user can search for `new` and see the new icons. or maybe we'd like to enhance the UI to display it.

**Comment by ericsoderberghp** [comment]
How about just a "New!" section towards the top that highlights them? I don't know that it necessarily has to be a sort option across all icons.

**Comment by ShimiSun** [comment]
Yep, that sounds fun to me. @JetLim or @L0ZZI care to work on the design?

**Comment by JetLim** [comment]
yes. let me carry this one! @L0ZZI @ShimiSun @ericsoderberghp This should also go onto @MikeWalrath roadmap?

**Comment by ShimiSun** [comment]
I think of the roadmap as more of a list for future enhancements we'd like to accomplish, so I think this issue ticket is enough for tracking.

**Comment by taysea** [comment]
This feels stale, closing for now. We can re-open if the request comes up.
