### ISSUE TITLE
Kebab Icon

### ISSUE THREAD

**Issue by SukantPal** [grommet/grommet-icons#122]
I think the kebab icon is important and should be included in this library.

**Comment by ShimiSun** [comment]
What's the use case buddy? Can you share a design

**Comment by SukantPal** [comment]
The kebab icon is used extensively in Android (top-right menu icon in bar activities) and is a core part of material design.

https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwinmJCB74TkAhWI1FkKHW37ApUQjRx6BAgBEAQ&url=https%3A%2F%2Fdocs.woocommerce.com%2Fdocument%2Fandroid%2Fwoo-android-toolbar-menu%2F&psig=AOvVaw0WJmjfNGGfSauFhQ6dt5B9&ust=1565958189871139

**Comment by SukantPal** [comment]
By kebab, I mean the vertically stacked three dots. Not any other "food"-related icon.
