### ISSUE TITLE
Add Gatsby icon.

### ISSUE THREAD

**Issue by metinsenturk** [grommet/grommet-icons#123]
I believe GatsbyJS icon would be a nice addition.

**Comment by ShimiSun** [comment]
@JetLim care to work on a new logo?

**Comment by metinsenturk** [comment]
Icons for switching dark/ light themes are also needed. Currently, I am using `<Action />` and `<Actions />` to represent dark and light themes, respectively. There are multiple themes in Grommet, some icons would be nice to represent them.

**Comment by JetLim** [comment]
Example. The logo ready for review. 

![logo](https://user-images.githubusercontent.com/16657091/58507235-1f0ab500-8146-11e9-8f6e-43fee137b684.png)

**Comment by ericsoderberghp** [comment]
> Icons for switching dark/ light themes are also needed. Currently, I am using `<Action />` and `<Actions />` to represent dark and light themes, respectively. There are multiple themes in Grommet, some icons would be nice to represent them.

This sounds like possibly a separate issue. Do you mean an icon to use with a control that switches between dark and light themes? Or, do you mean that each theme should have an icon that could be used in a control to select the desired theme?

**Comment by ShimiSun** [comment]
@metinsenturk can you please let us know what you think ⬆️ ?

**Comment by metinsenturk** [comment]
@ShimiSun Thank you! Looks amazing. I will give it a try.

**Comment by ShimiSun** [comment]
Closing the issue, Gatsby icon is added https://icons.grommet.io/?s=Gatsb
