### ISSUE TITLE
Update Red Hat logo

### ISSUE THREAD

**Issue by sofiageo** [grommet/grommet-icons#124]
Just a thing I noticed when searching for icons. 

https://www.redhat.com/en/about/brand/new-brand

**Comment by ShimiSun** [comment]
@JetLim will you take a look at this one?

**Comment by JetLim** [comment]
The logo ready for review. @ShimiSun pls check email for the attached asset.
Visual Example

<img width="284" alt="redhat" src="https://user-images.githubusercontent.com/16657091/58647036-8bf38b80-82bb-11e9-847e-08dd53012da9.png">

**Comment by ShimiSun** [comment]
Released on 4.3.0 https://github.com/grommet/grommet-icons/releases/tag/v4.3.0
