### ISSUE TITLE
<More/> icon is missing vertical format

### ISSUE THREAD

**Issue by bytewoopy** [grommet/grommet-icons#128]
I can't seem to find a vertical format for the more Icon: https://www.iconfinder.com/icons/1137487/dots_menu_more_navigation_option_options_icon

Need to use this for menu actions in some places, and the vertical fits better, similar to Google Drive.

**Comment by ShimiSun** [comment]
@ericsoderberghp I'm thinking maybe we can add a feature that allows rotations of the icons?

**Comment by ericsoderberghp** [comment]
Hmm... Let's discuss with @L0ZZI. I suspect rotation doesn't really work for most icons. I'm wondering if this is a special case and we should just have another icon called something like MoreVertical?
