### ISSUE TITLE
Add a GraphQL Icon

### ISSUE THREAD

**Issue by daphnecharles** [grommet/grommet-icons#129]
Hey I love all the icons provided so far, and I think a good addition would be a GraphQL icon.

**Comment by L0ZZI** [comment]
![graph-ql@2x](https://user-images.githubusercontent.com/1753301/61308855-fbf39d80-a7a5-11e9-8550-d71f06707088.png)
[graph-ql.zip](https://github.com/grommet/grommet-icons/files/3397913/graph-ql.zip)
