### ISSUE TITLE
List Icon ?

### ISSUE THREAD

**Issue by Serexx** [grommet/grommet-icons#13]
'Return to List' is a common need in CRUD ops - typically we've used a 'bulleted list' icon to represent that action. It is normally similar to the existing Grommet-Icons Task Icon but with bullets rather than checkmarks. Would love to have one in this library!

**Comment by dgennetten** [comment]
How about the Sort icon? http://grommet.io/grommet-icons/?s=Sort

**Comment by Serexx** [comment]
Thanks looked at them, but their intent seems clear and in our context would likely cause some confusion were we to then use them to provide list sorting. For now we are using the 3-bar 'Menu' ('hamburger') icon and adding a label. There is less potential for misinterpretation as its only other use is in the navigation sidebar, in smaller view ports. That said, we think a separate 'list' icon would be better - some good examples in various libraries on icomoon.io :-)

**Comment by alansouzati** [comment]
hey @Serexx would you have an image of the image that you can upload here so that we can evaluate?

**Comment by Serexx** [comment]
Easiest may be to go to icomoon.io
[here](https://icomoon.io/app/#/select)
and search for 'list' - there are several versions from various libraries (ordered and unordered lists) some are free others are not (click an icon in a library to find which is which) - I've preferred the 'Feather', 'Material' or 'Font Awesome' versions - Once you select an icon the Raw SVG is available through the 'Generate SVG' link in the page footer. Hope that helps!

**Comment by L0ZZI** [comment]
Updated https://github.com/grommet/grommet-icons/pull/91

**Comment by L0ZZI** [comment]
https://icons.grommet.io/?s=list
