### ISSUE TITLE
Please export the <Hide/> and <FormHide/> icons too

### ISSUE THREAD

**Issue by jermsam** [grommet/grommet-icons#130]
Here is the sandbox reproducing the fact that the `Hide` icon is not exported by the `grommet-icons` library:
https://codesandbox.io/s/grommet-icons-8bmz5

**Comment by ShimiSun** [comment]
Available on grommet-icons release 4.3.0 https://github.com/grommet/grommet-icons/releases/tag/v4.3.0.
Thank you for your patient.
