### ISSUE TITLE
Dependency on styled-components

### ISSUE THREAD

**Issue by loktar00** [grommet/grommet-icons#135]
Receive this error when trying to just use the icon library by itself,

```
ERROR in ./node_modules/grommet-icons/es6/StyledIcon.js
Module not found: Error: Can't resolve 'styled-components' in ****node_modules\grommet-icons\es6'
```

Adding styled-components into the root project allows a user to continue, ideally though the base project wouldn't require `styled-components` as a hard requirement, alternatively it could be listed in the readme as a requirement for the library.

**Comment by ShimiSun** [comment]
Quoting from https://github.com/grommet/grommet/issues/3770:

Hey there,

styled-components is intentionally a peer dependency so we don't lock you in our version of styled-components. Same with react!
This is not a bug but a feature :)
