### ISSUE TITLE
Dynamic Icon

### ISSUE THREAD

**Issue by diegouploads** [grommet/grommet-icons#137]
Isn't there a way to pass a dynamic icon?
example below:
import {Icon} from "grommet-icons";

<Icon name = "Cart">

**Comment by oorestisime** [comment]
Maybe related to #87 
Does `Blank` respond to what you need?

**Comment by diegouploads** [comment]
> Talvez relacionado a [# 87](https://github.com/grommet/grommet-icons/issues/87)
> Será que `Blank`responder ao que você precisa?

Can you give me an example of how to pass car inside blank

**Comment by oorestisime** [comment]
Not sure what you mean. which car?

**Comment by diegouploads** [comment]
> Não tenho certeza do que você quer dizer. qual carro?

The "Car" or "Bar" Icon Inside Blank

**Comment by oorestisime** [comment]
But why would you want to do this? What are you trying to do actually?
The Blank icon is meant to be used like:

```
<Blank
      viewBox='0 0 24 24'
    >
      <path d='' />
    </Blank>
```

so i am not sure what you are trying to achieve here. If you could give a bit more details it will be great!

**Comment by diegouploads** [comment]
> Mas por que você quer fazer isso? O que você está tentando fazer realmente? 
> O ícone em branco destina-se a ser usado como:
> 
> ```
> <Blank
>       viewBox='0 0 24 24'
>     >
>       <path d='' />
>     </Blank>
> ```
> 
> então eu não tenho certeza do que você está tentando alcançar aqui. Se você pudesse dar um pouco mais de detalhes, seria ótimo!



> But why would you want to do this? What are you trying to do actually?
> The Blank icon is meant to be used like:
> 
> ```
> <Blank
>       viewBox='0 0 24 24'
>     >
>       <path d='' />
>     </Blank>
> ```
> 
> so i am not sure what you are trying to achieve here. If you could give a bit more details it will be great!

Modelo de como eu gostaria, pois preciso passar o nome do icone dinamicamente;
 
 array.map( a => {
    return(
        <Blank name={a.nameIcon} viewBox='0 0 24 24' ><path d='' /></Blank>
    )
})

**Comment by oorestisime** [comment]
How about something like?

```
import { Car, Bar } from "grommet-icons"

const icons = {
  car: Car,
  bar: Bar,
}
icons.map(Icon => <Icon />)

```

**Comment by diegouploads** [comment]
> How about something like?
> 
> ```
> import { Car, Bar } from "grommet-icons"
> 
> const icons = [Car, Bar]
> icons.map(Icon => <Icon />)
> ```

This is not for me, I have more than 30 categories that comes from the database, I need to validate if it is the category and show the icon, if I can pass the name inside the tag would be perfect if I do not have to import everything before and do several if

**Comment by oorestisime** [comment]
I guess you can have an external file doing all the mappings for you.

Or *and this is not the best idea since you will import all the icons and not benefit from tree-shaking* you can `import * as icons from "grommet-icons"` and then do `icons[key]`. But again this is not a great idea since you will import all the icons in your build and increase your bundle size.

**Comment by diegouploads** [comment]
Today I am doing this and it works, but I would like to change as I have over 40 icons.

`import React from 'react';
import {
    Cafeteria, Cloud, Bar, CreditCard, Home, Shop,
} from "grommet-icons";

export const Icone = ({name, color = "#fff", size = "14px"}) => {
    if (name === 'Cafeteria') return <Cafeteria color={color} size={size} />;
    if (name === 'Cloud') return <Cloud color={color} size={size} />;
    if (name === 'Bar') return <Bar color={color} size={size} />;
    if (name === 'CreditCard') return <CreditCard color={color} size={size} />;
    if (name === 'Home') return <Home color={color} size={size} />;
    if (name === 'Shop') return <Shop color={color} size={size} />;
}`

**Comment by diegouploads** [comment]
> Today I am doing this and it works, but I would like to change as I have over 40 icons.
> 
> `import React from 'react';
> import {
> Cafeteria, Cloud, Bar, CreditCard, Home, Shop,
> } from "grommet-icons";
> 
> export const Icone = ({name, color = "#fff", size = "14px"}) => {
> if (name === 'Cafeteria') return ;
> if (name === 'Cloud') return ;
> if (name === 'Bar') return ;
> if (name === 'CreditCard') return ;
> if (name === 'Home') return ;
> if (name === 'Shop') return ;
> }`

`<Icone name="Bar" color="#000" />`

**Comment by oorestisime** [comment]
But you don't need to do all those ifs.
Just create a map between name and icon

```
import {Car, Bar, Cloud} from "grommet-icons"
const icons = {
  cloud: Cloud,
  car: Car,
  bar: Bar,
}

array.map(icon => {const Icon = icons[icon]; return <Icon />})
```

**Comment by diegouploads** [comment]
> riar um mapa entre o nome e o ícone

True, I'll do it, I'll be back with result.

**Comment by diegouploads** [comment]
It worked, thank you very much!

**Comment by ShimiSun** [comment]
Thank you for resolving it! 🎉
