### ISSUE TITLE
Cannot import <MoreVertical>

### ISSUE THREAD

**Issue by bytewoopy** [grommet/grommet-icons#142]
It seems I cannot import the **MoreVertical** icon that was added in a recent release, tested it in 4.3.0 release of grommet icons. Please see sandbox (icon is un commented)

https://codesandbox.io/embed/more-vertical-opix5

**Comment by bytewoopy** [comment]
Bump... any ideas?

**Comment by dariawhitecastle** [comment]
Same here.

**Comment by ShimiSun** [comment]
Thank you for your patient,
grommet icons 4.4.0 is released https://github.com/grommet/grommet-icons/releases/tag/v4.4.0

This is an example of the MoreVertical icon:
https://codesandbox.io/s/morevertical-pcvoe

I'll be closing this issue.
