### ISSUE TITLE
Adding a Telegram icon

### ISSUE THREAD

**Issue by nomadus** [grommet/grommet-icons#143]
As this messenger is getting popular, could you please add the Telegram icon? Thanks in advance!

**Comment by TimPchelintsev** [comment]
["Send" icon](https://icons.grommet.io/?s=send) is very similar, btw:)

**Comment by ShimiSun** [comment]
https://telegram.org/

**Comment by nomadus** [comment]
Yes, they are similar, but the logo has color.

**Comment by ShimiSun** [comment]
Icon accepts the `color` prop, can you try to fetch it with the color?

**Comment by L0ZZI** [comment]
Does `send` work for your need? https://icons.grommet.io/?s=send

**Comment by nomadus** [comment]
I guess I can use the send icon, thanks!

**Comment by ShimiSun** [comment]
Thanks! I'll be closing this issue, feel free to open a new one in case you need anything else.
