### ISSUE TITLE
New Expand All Icon Request

### ISSUE THREAD

**Issue by chesleyratliff** [grommet/grommet-icons#157]
I'd like to see an "expand all" icon from grommet so that a group of collapsed fields can all be opened by clicking one icon.

**Comment by chesleyratliff** [comment]
I'd also of course like to see a corresponding collapse all icon

**Comment by taysea** [comment]
@chesleyratliff Doing some cleanup on grommet-icons project. Is this request still needed? In most cases I'd seen, we use the "Down"/"Up" icons to indicate expand/collapse. If you're thinking of something different, can you provide a visual/link to a visual?

If this is stale, feel free to close the issue.

**Comment by chesleyratliff** [comment]
@taysea yeah I have no recollection why I asked for this 3.5 years ago so you can close this.
