### ISSUE TITLE
Icon Qr looks weird.

### ISSUE THREAD

**Issue by jim-king-2000** [grommet/grommet-icons#159]
1. Go to 'https://github.com/jim-king-2000/nextbugrepro', clone the code.
2. cd nextbugrepro, npm run dev.
3. Open "localhost:3000" in browser, see the icon.

**Comment by ShimiSun** [comment]
Hi @jim-king-2000, thanks for reporting, we are in the process of fixing this issue, in the meanwhile use `color="plain"` it should work as expected.

PR #163 is a WIP and related to this issue.

**Comment by ShimiSun** [comment]
@L0ZZI we need an updated Qr icon that is compliant with the conditions raised on PR #163

**Comment by saggiemilva** [comment]
[qr.svg.zip](https://github.com/grommet/grommet-icons/files/4584071/qr.svg.zip)
**Metadata**
QR, Technology, Scan
