### ISSUE TITLE
Add Last.fm icon

### ISSUE THREAD

**Issue by LRNZ09** [grommet/grommet-icons#160]
It would be a nice addition to having the Last.fm icon within this package.

**Comment by ShimiSun** [comment]
Can you share a link to what you had in mind?

**Comment by LRNZ09** [comment]
> Can you share a link to what you had in mind?

Sure! Maybe something like the squared one here https://fontawesome.com/icons?d=gallery&q=lastfm&s=brands

**Comment by L0ZZI** [comment]
Done!

[lastfm.svg.zip](https://github.com/grommet/grommet-icons/files/4356443/lastfm.svg.zip)

**Comment by LRNZ09** [comment]
Thanks! Do you know when it'll be available in the package?

**Comment by ShimiSun** [comment]
@LRNZ09  we are not sure when the official release will take place, but you can point your grommet-icons package (on package.json) to "https://github.com/grommet/grommet/tarball/stable" and enjoy the new icon.

**Comment by LRNZ09** [comment]
Perfect, thanks a lot for your work!
