### ISSUE TITLE
Add Ebay icon

### ISSUE THREAD

**Issue by markjackson02** [grommet/grommet-icons#162]

**Comment by L0ZZI** [comment]
Done!

[ebay.svg.zip](https://github.com/grommet/grommet-icons/files/4356440/ebay.svg.zip)

**Comment by ShimiSun** [comment]
@markjackson02  we are not sure when the official release will take place, but you can point your grommet-icons package (on package.json) to "https://github.com/grommet/grommet/tarball/stable" and enjoy the new icon.
