### ISSUE TITLE
Add icons for light/dark mode switching

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet-icons#166]
Sun/Moon (outline/filled)
Lit and unlit lightbulb
Etc

**Comment by ShimiSun** [comment]
@L0ZZI can we consider moving the dark/light icons from the design-system to grommet icons?

**Comment by saggiemilva** [comment]
[moon.svg.zip](https://github.com/grommet/grommet-icons/files/4584038/moon.svg.zip)
**Metadata**
Moon, Dark

[sun.svg.zip](https://github.com/grommet/grommet-icons/files/4584040/sun.svg.zip)
**Metadata**
Sun, Light
