### ISSUE TITLE
Mobile Device Icon

### ISSUE THREAD

**Issue by berkayk** [grommet/grommet-icons#167]
Thanks for this awesome set.

I am having trouble finding a suitable icon for Mobile devices. I need a mobile device icon similar to **Desktop** or **PersonalComputer**.

**Comment by saggiemilva** [comment]
[phone-flip.svg.zip](https://github.com/grommet/grommet-icons/files/4588008/phone-flip.svg.zip)
**Metadata**
FlipPhone, Technology, Mobile, Device

[phone-horz.svg.zip](https://github.com/grommet/grommet-icons/files/4588018/phone-horz.svg.zip)
**Metadata**
PhoneHorizontal, Technology, Mobile, Device

[phone-vert.svg.zip](https://github.com/grommet/grommet-icons/files/4588026/phone-vert.svg.zip)
**Metadata**
PhoneVertical, Technology, Mobile, Device

**Comment by ShimiSun** [comment]
I'll be renaming:
`phone-horz.svg` to `phone-horizontal.svg`
and similarly with vertical.
