### ISSUE TITLE
Box gap prop rendering gaps between null children

### ISSUE THREAD

**Issue by nateq314** [grommet/grommet-icons#169]
```JSX
<Box direction="row" gap="10px">
  {null}
  {null}
  {null}
  <Something />
</Box>
```
is rendering 3 gaps, whereas common sense would dictate that there should be none, as there is only one non-null child element.

**Comment by ShimiSun** [comment]
Thanks for reporting buddy, can you file this issue under [grommet itself](https://github.com/grommet/grommet/issues) and not under grommet-icons?

**Comment by nateq314** [comment]
Oops my bad! Here it is: https://github.com/grommet/grommet/issues/3999. Closing this one.
