### ISSUE TITLE
Please add zoom logo

### ISSUE THREAD

**Issue by nomadus** [grommet/grommet-icons#172]

**Comment by saggiemilva** [comment]
[zoom.svg.zip](https://github.com/grommet/grommet-icons/files/4595724/zoom.svg.zip)
**Metadata**
Zoom, Social, Video, Chat, Talk

**Comment by ShimiSun** [comment]
@saggiemilva look how quick you are! 😉 hoping I'll get to it in the next couple of days.

**Comment by ShimiSun** [comment]
Hi @saggiemilva the svg isn't translated well, here is the complied component:
```
import React from 'react';

import { StyledIcon } from '../StyledIcon';

export const Zoom = props => (
  <StyledIcon viewBox='0 0 24 24' a11yTitle='Zoom' {...props}>
    <rect width='24' height='24' rx='8' fill='url(#paint0_linear)' /><path fillRule='evenodd' clipRule='evenodd' d='M6 8C5.44772 8 5 8.44772 5 9V13C5 14.6569 6.34315 16 8 16H14C14.5523 16 15 15.5523 15 15V11C15 9.34315 13.6569 8 12 8H6ZM15.9948 10.4345C15.6758 10.799 15.5 11.267 15.5 11.7515V12.2485C15.5 12.733 15.6758 13.201 15.9948 13.5655L17.6856 15.4978C18.1416 16.019 19 15.6964 19 15.0039V8.99609C19 8.30356 18.1416 7.98103 17.6856 8.50221L15.9948 10.4345Z' fill='white' />
  </StyledIcon>
);
```

It is basically shown as a square with round corners
![image](https://user-images.githubusercontent.com/6320236/81434523-86d1ca00-9123-11ea-9236-a9bac0edc73c.png)


Can you please take another look on the svg?

**Comment by saggiemilva** [comment]
New zoom icon
[zoom.svg.zip](https://github.com/grommet/grommet-icons/files/4616482/zoom.svg.zip)
**Metadat**
Zoom, Social, Video, Chat, Talk

**Comment by ShimiSun** [comment]
@saggiemilva I tried this one and it doesn't work even on a default mode:
![image](https://user-images.githubusercontent.com/6320236/81716921-2f8b6c80-9437-11ea-9ab3-3d218ea8776c.png)

**Comment by saggiemilva** [comment]
Darn, I thought removing the gradient would work. Let's try this one:
[zoom.svg.zip](https://github.com/grommet/grommet-icons/files/4617357/zoom.svg.zip)
