### ISSUE TITLE
Icons from Figma

### ISSUE THREAD

**Issue by saggiemilva** [grommet/grommet-icons#174]
A handful of Icons have been added to the Figma library by request and not they need to be added to the Grommet library.

[table.svg.zip](https://github.com/grommet/grommet-icons/files/4616630/table.svg.zip)
**Metadata**
Table, Chart, Data

[time.svg.zip](https://github.com/grommet/grommet-icons/files/4616632/time.svg.zip)
**Metadata**
Time, Chart, Line, Data

[package.svg.zip](https://github.com/grommet/grommet-icons/files/4616647/package.svg.zip)
**Metadata**
Package, Controls, Box

[apps.svg.zip](https://github.com/grommet/grommet-icons/files/4616667/apps.svg.zip)
**Metadata**
Apps, Core

[clock.svg.zip](https://github.com/grommet/grommet-icons/files/4616670/clock.svg.zip)
**Metadata**
Clock, Time, Core

[console.svg.zip](https://github.com/grommet/grommet-icons/files/4616842/console.svg.zip)
**Metadata**
Console, Core

[flows.svg.zip](https://github.com/grommet/grommet-icons/files/4616843/flows.svg.zip)
**Metadata**
Flows, Core

[help.svg.zip](https://github.com/grommet/grommet-icons/files/4616847/help.svg.zip)
**Metadata**
Help, Core, Question

[home.svg.zip](https://github.com/grommet/grommet-icons/files/4616854/home.svg.zip)
**Metadata**
Home, Core

[share-option.svg.zip](https://github.com/grommet/grommet-icons/files/4616858/share-option.svg.zip)
**Metadata**
Share, Core

[gem.svg.zip](https://github.com/grommet/grommet-icons/files/4616895/gem.svg.zip)
**Metadata**
Gem, Miscellaneous

[license.svg.zip](https://github.com/grommet/grommet-icons/files/4616901/license.svg.zip)
**Metadata**
License, Miscellaneous

[script.svg.zip](https://github.com/grommet/grommet-icons/files/4616903/script.svg.zip)
**Metadata**
Script, Miscellaneous

[download-option.svg.zip](https://github.com/grommet/grommet-icons/files/4616914/download-option.svg.zip)
**Metadata**
Download, Navigation, Arrow

[upload-option.svg.zip](https://github.com/grommet/grommet-icons/files/4616918/upload-option.svg.zip)
**Metadata**
Upload, Navigation, Arrow

[disabled-outline.svg.zip](https://github.com/grommet/grommet-icons/files/4616935/disabled-outline.svg.zip)
**Metadata**
Disabled, Status

[ezmeral.svg.zip](https://github.com/grommet/grommet-icons/files/4616949/ezmeral.svg.zip)
**Metadata**
Ezmeral, Platform

[tictok.svg.zip](https://github.com/grommet/grommet-icons/files/4616964/tictok.svg.zip)
**Metadata**
Tictok, Social

[beacon.svg.zip](https://github.com/grommet/grommet-icons/files/4617024/beacon.svg.zip)
**Metadata**
Beacon, Technology

[blades-horz.svg.zip](https://github.com/grommet/grommet-icons/files/4617035/blades-horz.svg.zip)
**Metadata**
Blades-Horizontal, Technology

[blades-vert.svg.zip](https://github.com/grommet/grommet-icons/files/4617039/blades-vert.svg.zip)
**Metadata**
Blades-Vertical, Technology

[camera.svg.zip](https://github.com/grommet/grommet-icons/files/4617043/camera.svg.zip)
**Metadata**
Camera, Technology

[cpu.svg.zip](https://github.com/grommet/grommet-icons/files/4617045/cpu.svg.zip)
**Metadata**
cpu, Technology

[fan-option.svg.zip](https://github.com/grommet/grommet-icons/files/4617048/fan-option.svg.zip)
**Metadata**
Fan, Technology

[fan.svg.zip](https://github.com/grommet/grommet-icons/files/4617052/fan.svg.zip)
**Metadata**
Fan, Technology

[firewall.svg.zip](https://github.com/grommet/grommet-icons/files/4617055/firewall.svg.zip)
**Metadata**
Firewall, Technology

[gateway.svg.zip](https://github.com/grommet/grommet-icons/files/4617068/gateway.svg.zip)
**Metadata**
Gateway, Technology

[keyboard.svg.zip](https://github.com/grommet/grommet-icons/files/4617072/keyboard.svg.zip)
**Metadata**
Keyboard, Technology

[memory.svg.zip](https://github.com/grommet/grommet-icons/files/4617081/memory.svg.zip)
**Metadata**
Memory, Technology

[mouse.svg.zip](https://github.com/grommet/grommet-icons/files/4617086/mouse.svg.zip)
**Metadata**
Mouse, Technology

[network-drive.svg.zip](https://github.com/grommet/grommet-icons/files/4617098/network-drive.svg.zip)
**Metadata**
Network-Drive, Technology, Network

[plug.svg.zip](https://github.com/grommet/grommet-icons/files/4617102/plug.svg.zip)
**Metadata**
Plug, Technology

[sans.svg.zip](https://github.com/grommet/grommet-icons/files/4617108/sans.svg.zip)
**Metadata**
Sans, Technology

[sd.svg.zip](https://github.com/grommet/grommet-icons/files/4617111/sd.svg.zip)
**Metadata**
sd, Technology

[switch.svg.zip](https://github.com/grommet/grommet-icons/files/4617115/switch.svg.zip)
**Metadata**
Switch, Technology

[usb-key.svg.zip](https://github.com/grommet/grommet-icons/files/4617117/usb-key.svg.zip)
**Metadata**
usb-key, usb, Technology

**Comment by ShimiSun** [comment]
we currently have a Table icon, is the attached icon supposed to replace the existing one? https://icons.grommet.io/?s=table

**Comment by saggiemilva** [comment]
I talked with Chris and he said to leave the current Table icon and to forget about the new one.

**Comment by ShimiSun** [comment]
@saggiemilva we currently have a Apps icon, is the attached icon supposed to replace the existing one?
https://icons.grommet.io/?s=apps

**Comment by saggiemilva** [comment]
Yes, the new Apps icon should replace the current one on grommet and make the current Apps icon a Grid-Option icon

**Comment by ShimiSun** [comment]
@saggiemilva Thanks!

making sure you didn't miss the rest of the comment:
>Same for Clock, Home, ShareOption, License, Camera, Fan and Help icons.

**Comment by saggiemilva** [comment]
Oh sorry, I did miss that. 
-Clock, Help, and License should replace current icon

-Home and Fan should become secondary options 

-Keep the current camera icon as is and add the new one as Webcam

- The new share can replace Share-Option, and the existing Share-Option can be renamed Link-Option

**Comment by IanKBovard** [comment]
@saggiemilva Could you clarify for me what you mean by making home and fan secondary options? Add them with a new name HomeOption and FanOption(i see we already have a fan and fanoption)? Also, it looks like we have a keyboard icon as well. Do we want to replace it?

**Comment by saggiemilva** [comment]
@IanKBovard – Add the new home icon as HomeOption and replace the old FanOption with the new one (since currently its just a black box). For keyboard, just replace the old icon with the new.

**Comment by IanKBovard** [comment]
gotcha, thanks!
