### ISSUE TITLE
Moon icon missing

### ISSUE THREAD

**Issue by adampblack** [grommet/grommet-icons#184]
Attempted import error: 'Moon' is not exported from 'grommet-icons'.

node_modules\grommet-icons\icons

There is no Moon.js file

**Comment by adampblack** [comment]
There is no Sun.js file also.

There are 564 icon files.

There are 598 icons showing on the public webpage.
https://icons.grommet.io/ 

So two mentioned are 2 of 34 from my count.

**Comment by JeremyPittard** [comment]
I think this ties in with #182 
looks as if the code for each icon is in the repo

**Comment by ShimiSun** [comment]
Correct, In the meanwhile, you can use the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) to receive the new icons. we are still working on some fixes before publishing to NPM.
Here is a code example: https://github.com/hpe-design/design-system/blob/7de5860ac55713b79ea41172a73dc4dd23750fd4/aries-site/package.json#L11

**Comment by adampblack** [comment]
Thanks, closing issue
