### ISSUE TITLE
GooglePlay icon group broken

### ISSUE THREAD

**Issue by StefanoDeVuono** [grommet/grommet-icons#187]
The google play icon is wrapped a a `<g>` tag and when I color the icon, it disappears

ie
```
{<GooglePlay color="plain" />}
```
renders fine, but

```
{<GooglePlay color="orange" />}
```
does not.

It generates the following HTML:
```
<svg aria-label="GooglePlay" viewBox="0 0 24 24" class="StyledIcon-ofa7kd-0 bfWHQO" style="">
    <g fill="none" fill-rule="evenodd">
        <polygon stroke="#444" stroke-linejoin="round" stroke-width="2" points="3 2 3 22 21 12"></polygon>
        <path stroke="#444" stroke-width="2" d="M3,2 L14,16"></path>
        <path stroke="#444" stroke-width="2" d="M3,8 L14,22" transform="matrix(1 0 0 -1 0 30)"></path>
    </g>
</svg>
```
And nothing shows up.

When I check the inspector, the `<g>` tag has the following CSS associated with it:
<img width="254" alt="Screen Shot 2020-06-30 at 4 38 55 PM" src="https://user-images.githubusercontent.com/2316641/86187342-6c4b1a00-baf0-11ea-9b5b-af20c5a27299.png">

If I remove the `<polygon>` and 2 `<path>` tags from inside the `<g>` tag, I have the following HTML:
```
<svg aria-label="GooglePlay" viewBox="0 0 24 24" class="StyledIcon-ofa7kd-0 bfWHQO" style="">
        <polygon stroke="#444" stroke-linejoin="round" stroke-width="2" points="3 2 3 22 21 12"></polygon>
        <path stroke="#444" stroke-width="2" d="M3,2 L14,16"></path>
        <path stroke="#444" stroke-width="2" d="M3,8 L14,22" transform="matrix(1 0 0 -1 0 30)"></path>
</svg>
``` 

And the `<polygon>` and 2 `<path>` tags have the following CSS associated with them:
<img width="253" alt="Screen Shot 2020-06-30 at 4 39 56 PM" src="https://user-images.githubusercontent.com/2316641/86187539-debbfa00-baf0-11ea-80ef-3660ba99469d.png">

So, I think this can be fixed by explicitly adding a `stroke: inherit;` style to the `<g>` tag or removing the `<g>` tag completely.

I'm happy to put up a PR doing either.

**Comment by taysea** [comment]
Fixed by #323
