### ISSUE TITLE
Add status alert icon

### ISSUE THREAD

**Issue by vavalos5** [grommet/grommet-icons#198]
[circle-alert.svg.zip](https://github.com/grommet/grommet-icons/files/4997541/circle-alert.svg.zip)

**Comment by ShimiSun** [comment]
@IanKBovard Please add this to the library to help with the design system work.

**Comment by IanKBovard** [comment]
@vavalos5 What would the metadata be for this icon? just double checking, but the icon will be called status-alert, not circle-alert?

**Comment by vavalos5** [comment]
@IanKBovard Thanks for double checking. The icon will be called circle-alert

**Comment by vavalos5** [comment]
Status, alert, validation

**Comment by IanKBovard** [comment]
great, thanks!
