### ISSUE TITLE
Better search tagging

### ISSUE THREAD

**Issue by RyanCCollins** [grommet/grommet-icons#2]
Love the new site!  Very clever 😄 

As a frequent user of the old icon docs, one of my biggest pet peeves was that I could hardly ever find the icon I was looking for if I did not know the name of it.  

For example, try finding a "Rocket" if you do not know that the icon is named "Deploy".  I'd like to propose that we add a tagging system to the new documentation site so that icons can be tagged with multiple words to make searching for them by their content easier.

Please let me know what you think!

**Comment by alansouzati** [comment]
Thanks for the kind words @RyanCCollins :)

That's a very good idea. In fact I've already started a similarity search in the site. But I got lazy to fill in all the synonyms for all the 521 icons 😅 

I added to around 100. Do you want to chime in and help adding more? Just augment this [metadata](https://github.com/grommet/grommet-icons/blob/master/src/js/metadata.js) file and I will make sure to redeploy the site as we grow that document.

**Comment by RyanCCollins** [comment]
Yea, I'd love to!

**Comment by dgennetten** [comment]
I think also the current sub-string match isn't ideal.  "edit" shouldn't associate "CreditCard"

**Comment by dgennetten** [comment]
I have a PR with new tags added to icons listed in current metadata.js; fixed a couple typos.

**Comment by RyanCCollins** [comment]
Nice thanks @dgennetten!

**Comment by alansouzati** [comment]
hey @dgennetten thanks for you PR, I'm glad you are joining the effort. I will review it soon. 

My idea is to keep the search match really simple. Although, I see your point that typing `edit` and seeing `CreditCard` may not be helpful, but I don't think it hurts either.

We have a bunch of icons that start with `Form`, so typing `subtract` should return `FormSubtract`. We could easily fix that by adding `subtract` to `FormSubtract` [entry](https://github.com/grommet/grommet-icons/blob/master/src/js/metadata.js#L40),  but this is error prone as I'm sure we will find a bunch of cases where we will forget to add this entry. For example, `FormSearch` has `search` in its value, but `FormSubtract`does not. 

I don't think it hurts to add `up` to `CarrotDown`, but it feels weird to me as `up` is not a synonym to `down`. But I'm ok having that, if you guys think this would be helpful.

**Comment by dgennetten** [comment]
Thanks for the feedback @alansouzati. I think a policy -- driven by simplicity -- that gives a slight overreach (edit->CreditCard) is better than underreach.  Up can be considered a match for Down if you ultimately searching for direction icons (note, btw, that I added 'direction' and 'arrow' to all icons having any association with either). 

A long time ago, I suggested that we put our icons on public icon library sites just so we'd get this better searching experience, so I am delighted to contribute!

**Comment by alansouzati** [comment]
Agree with typing `direction` should return `up`, `down`, ...

> (note, btw, that I added 'direction' and 'arrow' to all icons having any association with either).

love that, let's start with this for now (we can always revisit this later if we feel the need for a better search algorithm).

**Comment by banada** [comment]
Not sure if this is part of this issue:

If you try to search 'Login', you get a result for 'Logi' but not the full 'Login'.

**Comment by ShimiSun** [comment]
@banada Thanks for catching this issue. 💯 
It seems like a different issue than this thread, and it should be filed as a separate issue on [grommet-icons-site](https://github.com/grommet/grommet-icons-site/issues), particularly on the search component itself (rather than the metadata).
Feel free to file one.

**Comment by ShimiSun** [comment]
Since we significally improved the searc functionality, I'll be closing this issue. feel free to enhance the metadata as you think needed.

**Comment by banada** [comment]
Great, thank you!
