### ISSUE TITLE
Hamburger Menu is called "Menu" and conflicts with the component "Menu"

### ISSUE THREAD

**Issue by holdenmad** [grommet/grommet-icons#205]
Hi there! So it seems that the Hamburger Menu icon conflicts with the Grommet 'Menu' component when used together. 

`import {Menu} from 'grommet'`
`import {Menu} from 'grommet-icons'`

This produces an immediate error. Of course you can just use  "&#x2630;" to make a hamburger menu, but the icon component should probably be called "Hamburger" or "HamMenu" instead of "Menu".

**Comment by ShimiSun** [comment]
Due to backward compatibility, we can't change the name of the icon.
You can always import the icon with alias:
```
import { Menu as MenuIcon } from 'grommet-icons'; 
```
