### ISSUE TITLE
Request for new icons

### ISSUE THREAD

**Issue by kmar20** [grommet/grommet-icons#206]
Hi - We're using your icons on the Education pages to provide visual cues for the different types of courses we offer. (You can see them here: https://education.hpe.com/ww/en/training/delivery.html .) The icons for ILT, eLearning, and Digital Learner work, but the icon for VILT doesn't provide the visual cue we'd like. The "Workshop" icon is perfect for ILT, so we're wondering if it's possible to create a new one based on Workshop that signifies that it's virtual, not in person. This is NOT on demand; it's a live class that's taught in a virtual environment. Perhaps a calendar icon overlaid along the side of the Workshop icon? Or Workshop overlaid on a screen?

We're also updating the MyRoom page, and will be using UserExpert and UserAdd to indicate Basic and Premium subscription tiers; we need one more to depict the MyRoom University tier. Is it possible to create a new User icon with a graduation cap on? UserGrad? 

Let me know if you need any other info. Thanks so much!

**Comment by ShimiSun** [comment]
Hi buddy! Thank you for reaching out. I'd like to talk to you in more details about what you need and see whether/how we can match your needs. can you please reach out to me (shimi) on Slack so we can chat/call? http://slackin.grommet.io/

**Comment by ShimiSun** [comment]
Summary:

VILT - "virtual instructor-led training", which means it's a live class that people can take remotely.

The New icons request:
1. VILT - based on the "workshop" icon - workshop + desktop? something to indicate a virtual class
2. MyRoom - an icon based on "user" w/a graduation cap to represent the MyRoom University program

**Comment by L0ZZI** [comment]
My recommendation would be use the `workshop` icon as mentioned by @ShimiSun as it's tricky to convey the concept of virtual in the small size and we really want don't want to brand in icons that are more functional in use and application.

As for the User Grad we can add a cap to the set of user icons and add a PR to include it in the icon library.

**Comment by taysea** [comment]
Hi @kmar20 -- did the above suggestions get you unblocked? I'm going to close this ticket since it's been inactive for a while, but feel free to re-open if needed.
