### ISSUE TITLE
Spinning Icon

### ISSUE THREAD

**Issue by reddypramod85** [grommet/grommet-icons#220]
Do we have a spinning icon in V2 similar to V1?

https://v1.grommet.io/docs/spinning/

**Comment by ericsoderberghp** [comment]
not yet

**Comment by ericsoderberghp** [comment]
Here's an approach you could take: https://v2.grommet.io/box?c=DwIQ9gHgUABDAmBLATgUwMYBdFgHYF4AiZMAd0NhgCMxl5Vl8BvAbUriZgGdF6AuGAHIAhgBtRggDQx0YUbQGDSAC0SZUU7ogBeqRQFtUSAK77BMAL6T2MTj35DltHXkxjNs+ckVVkw3PCaPLqKXPpiEpbWcAC6FpQADsLwRIYm+hRwJMYBRABmxuKZMP6I4dh4zJyYAJ4JejDEYG7qAEqIAObKmITS8MZ+FbgCAEwArAAME5bxAPQAfEA

**Comment by jcfilben** [comment]
Closing since this can be achieved with the spinner component https://v2.grommet.io/spinner
