### ISSUE TITLE
[Bug] Icon "WifiLow" is not visible

### ISSUE THREAD

**Issue by MXXXXXS** [grommet/grommet-icons#224]
Bug reproduced here: https://codesandbox.io/s/elastic-cherry-3d4zm?file=/src/App.tsx

Seems to be caused by this line

https://github.com/grommet/grommet-icons/blob/2ee60efcb385ae6565fa5e0897e61cf3eda70c98/src/js/StyledIcon.js#L42

![demo](https://user-images.githubusercontent.com/28096993/111102146-5a2de080-8586-11eb-865b-66df94286429.png)

**Comment by ShimiSun** [comment]
Which grommet-icons version are you using? I think this issue was fixed on the latest version.

**Comment by MXXXXXS** [comment]
> Which grommet-icons version are you using? I think this issue was fixed on the latest version.

version 4.5.0

**Comment by ShimiSun** [comment]
You are correct, I've verified that WifiMedium, Wifi, WifiNone are working as expected, but not WifiLow.

**Comment by albertoncp** [comment]
we tried to make a pr to change the icon but it show this error

<img width="539" alt="Screenshot_7" src="https://user-images.githubusercontent.com/104977482/216826690-1ac3a9d3-6076-47f8-bf99-5d3f03bbcf05.png">
the ony problem to show the icon properly is to delete fillrule:"evenodd"

<img width="640" alt="Screenshot_6" src="https://user-images.githubusercontent.com/104977482/216826742-fae52763-02a3-4988-a98c-688a0319eb37.png">

**Comment by jcfilben** [comment]
Thanks for making a PR to fix this issue! Don't worry about the error from codeclimate, it is just complaining about similar blocks of code which is okay in this case.

**Comment by jcfilben** [comment]
Fixed in https://github.com/grommet/grommet-icons/pull/317
