### ISSUE TITLE
Spacing on right

### ISSUE THREAD

**Issue by EugeneGohh** [grommet/grommet-icons#226]
I have found this website doesn't look nice with the scrollbar to the right. Should we enhance the UI?

Here is the example:
![Untitled](https://user-images.githubusercontent.com/64187129/113082034-5946b100-920c-11eb-8cfb-513764d3066d.png)

**Comment by ShimiSun** [comment]
@EugeneGohh Feel free to make a contribution!

**Comment by EugeneGohh** [comment]
> @EugeneGohh Feel free to make a contribution!

Sorry I have opened the wrong link, I opened **Github Pages** link on the deployment one instead of  **.io** link. My bad for raising this issue.
