### ISSUE TITLE
"rem" size unit no longer support?

### ISSUE THREAD

**Issue by tholyong** [grommet/grommet-icons#239]
Hi,

I updated from v4.4.0 to 4.6.0. The icons with the custom size prop value e.g. "1.8rem" will be rendered as "1.8px". It can't support "rem" size unit currently? It works fine in v4.4.0. My root font-size value is 1rem equals to 10px.

**Comment by ThorNolan** [comment]
+1 for this issue, I was using grommet-icons v4.4.0 in a very large project, didn't have this problem until I recently updated my Nodejs version to 16.20.2 and then all icons stopped registering rem size and render with tiny px values. Wasn't an issue before on v4.4.0 but it seems like the error is still reproducible on that version. Hoping that PR #325  is merged soon, seems like a simple fix!
