### ISSUE TITLE
Twitter Icon Isn't Showing in Anchor

### ISSUE THREAD

**Issue by trippyml** [grommet/grommet-icons#264]
Thank you for this wonderful library. It looks like the Twitter icon isn't showing up in the Anchor tag when passed as an icon prop. I'm currently on version 4.6.2

```
<Anchor
      target="_blank"
      a11yTitle="Follow us on Twitter"
      href="https://twitter.com"
      icon={<Twitter color="brand" size="medium" />}
/>
```

**Comment by jcfilben** [comment]
Hi @trippyml here is a[ codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-g70pk?file=/index.js) showing the Twitter icon working in Anchor.

**Comment by trippyml** [comment]
Oh, wow. I just found out that Adblock was blocking this for me. I think I have more aggressive settings set. Thanks, I'll close this.
