### ISSUE TITLE
HomeRounded icon seems to be missing from exported icon library

### ISSUE THREAD

**Issue by eddieshowcase** [grommet/grommet-icons#265]
I see HomeRounded icon in both your Figma files and on the grommet icon website. I see the file in the source here in the repository.

However, it does NOT seem to be available or exported from the actual npm library package for use in code (we are using latest version 4.6.2). 

We would like to use this icon as it seems to be the suggested and most used 'home' icon across our designs.

<img width="1567" alt="Screen Shot 2021-11-18 at 9 25 23 AM" src="https://user-images.githubusercontent.com/7239901/142456012-599c96bf-4761-4bc9-b68f-0aa625d37b6f.png">

**Comment by eddieshowcase** [comment]
Looks like the export is just missing:

<img width="704" alt="Screen Shot 2021-11-18 at 9 45 06 AM" src="https://user-images.githubusercontent.com/7239901/142458993-441f4bfa-2014-43af-a884-f5f128fb9507.png">

**Comment by eddieshowcase** [comment]
Not sure how this relates to this issue: https://github.com/grommet/grommet-icons/issues/247

Also, I created a PR for this: https://github.com/grommet/grommet-icons/pull/266

**Comment by jcfilben** [comment]
Closing since #266 was merged and HomeRounded is available in v4.7.0
