### ISSUE TITLE
CircleAlert is rendering different icon than the site displays

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet-icons#286]
Circle Alert from the icon's [website ](https://icons.grommet.io/?s=circle)
![image](https://user-images.githubusercontent.com/6320236/191307030-43fdebc5-355b-444c-980f-491ed75cfcd6.png)

Rendering in development (ignore the color)
![image](https://user-images.githubusercontent.com/6320236/191307253-de796613-6585-4002-9159-96e1f8ec2cd1.png)

**Comment by jcfilben** [comment]
Related to https://github.com/grommet/grommet-icons/issues/275

**Comment by ShimiSun** [comment]
FYI, when I use `color="plain"` it does show as the website. But then I don't have control over the selected color.
