### ISSUE TITLE
Pulse icons, pulse!

### ISSUE THREAD

**Issue by davrodpin** [grommet/grommet-icons#3]
I have an icon suffering from a heart attack **right now** and its heart has to pulse back again!

I've tried to use grommet-icons along with the Pulse component from grommet, but found no much love.

```jsx
import Pulse from 'grommet/components/icons/Pulse';
import { Microphone } from 'grommet-icons';

...
    <Pulse icon={<Microphone size='large' />} />
...
```

Please, help me to save my icon!

**Comment by alansouzati** [comment]
Good point. We are currently evaluating the use of Pulse for Grommet 2.0. In the meantime we recommend using Grommet 1.x icons if you want to use Pulse.

**Comment by davrodpin** [comment]
> Good point. We are currently evaluating the use of Pulse for Grommet 2.0. In the meantime we recommend using Grommet 1.x icons if you want to use Pulse.

Thanks, @alansouzati. I will be switching to Grommet 1.x icons soon.
