### ISSUE TITLE
March Release

### ISSUE THREAD

**Issue by taysea** [grommet/grommet-icons#305]
Release latest on master to enabled theme release and grommet release.

**Comment by taysea** [comment]
# grommet-icon v4.10.0 Release Notes

- For themes that specify `theme.icon.disableScaleDown: true`, added functionality that applies `vector-effect="non-scaling-stroke"` to simple icons. Currently this flag only affects: Add, Checkmark, Close, Down, LinkDown, LinkNext, LinkPrevious, LinkUp, Next, Previous, Search, and Up (#301).
- Added `height` prop that will add top and bottom padding to align icon height with line-height of specified text t-shirt size (#303).
- Added `width` prop that will add left and right padding to align icon width with line-height of specified text t-shirt size (#304).

**Comment by jcfilben** [comment]
- We should add `theme.icon.disableScaleDown` to base.d.ts and to the docs.
- `height` and `width` props should be added to the docs.

**Comment by jcfilben** [comment]
After releasing we should update dependencies on grommet-icons

**Comment by jcfilben** [comment]
Dependency upgrade: https://github.com/grommet/grommet-icons/pull/306

**Comment by jcfilben** [comment]
Grommet-icons v4.10.0 has been released
