### ISSUE TITLE
How to decrease bundle size

### ISSUE THREAD

**Issue by nnurmano** [grommet/grommet-icons#307]
I have an app that uses grommet, grommet-icons and nextjs. The bundle size is huge and when I tried to analyze it, I see grommet-icons is taking most part of it. 

The icons are imported using:
`import {Attachment} from "grommet-icons";`
and components are imported using:
`import {Box} from "grommet";`

<img width="788" alt="Bundle" src="https://user-images.githubusercontent.com/3382143/225278877-bc2d852b-73b5-45a6-9914-6f5142deaac9.png">

What is the best practice to decrease the bundle size?

**Comment by ericsoderberghp** [comment]
`import { Accordion } from 'grommet-icons/icons/Accordion';`

**Comment by nnurmano** [comment]
Thanks, what I did is unified all the imports using the following example.
import {Apps, Close, Logout} from "grommet-icons";
The same I did for components imports. This reduced the bundle size by 50%,
