### ISSUE TITLE
[Icon Request] Important Icon

### ISSUE THREAD

**Issue by Lance-DC** [grommet/grommet-icons#313]
Please add an Important icon to the Grommet icons library.

**Comment by taysea** [comment]
Hi Lance, can you please provide a screenshot of what you might envision this icon to look like?

Would the "Alert" icon work for your use case?

**Comment by Lance-DC** [comment]
![image](https://github.com/grommet/grommet-icons/assets/46854319/d567a8b4-4757-4bd1-9f99-16aa0819daa9)

We already have three other use cases for the Alert icon. An additional icon for Important is still needed. It has a different connotation.

**Comment by taysea** [comment]
Would `CircleAlert` work?

<img width="148" alt="Screen Shot 2024-02-01 at 11 42 20 AM" src="https://github.com/grommet/grommet-icons/assets/12522275/5b004fc9-b03d-4741-9cee-81b82a325b2a">

**Comment by Lance-DC** [comment]
Yes, that works. For some reason we did not see that on the Grommet Icons site when we were looking for it last year.
