### ISSUE TITLE
Updated Social and Platform Icons

### ISSUE THREAD

**Issue by L0ZZI** [grommet/grommet-icons#321]
See, [Figma Sandbox](https://www.figma.com/file/PHNZD4cPd2xnfAeMYhYiSY/Expanded-Social-Icons?type=design&node-id=1%3A116&mode=design&t=IUWbpOF7wNWLXjNd-1).

I also took the liberty to scan the list of icon requests to capture any other icons in the request. 
Closes issues: #314, #261, #221, #188, #187, #126.

![social](https://github.com/grommet/grommet-icons/assets/1753301/b1b7d786-3ddb-40bb-873a-7a2ced207e21)

[updates-social-icons-svg.zip](https://github.com/grommet/grommet-icons/files/12254396/updates-social-icons-svg.zip)

**Comment by halocline** [comment]
@L0ZZI do we really have to update the X? ;)

**Comment by L0ZZI** [comment]
Right? 🤣 That and Spotify are the main asks because of corporate communications. Maybe another platform will come along...

**Comment by L0ZZI** [comment]
Added SVG exports.

**Comment by taysea** [comment]
This is closed by #322 #323
