### ISSUE TITLE
Icon dupe: schedule.js and plan.js.   Remove plan. Schedule alias includes 'plan'.

### ISSUE THREAD

**Issue by dgennetten** [grommet/grommet-icons#35]

**Comment by alansouzati** [comment]
that is true! thanks for identifying this. I will chat with @L0ZZI  today about it and see which one we should keep.

**Comment by L0ZZI** [comment]
PR pending, https://github.com/grommet/grommet-icons/pull/91

**Comment by L0ZZI** [comment]
Updated the schedule icon to a date number. See, https://icons.grommet.io/?s=schedule
