### ISSUE TITLE
Phone / Call / Mobile Icon

### ISSUE THREAD

**Issue by obfuscatedgeek** [grommet/grommet-icons#47]
Awesome set of icons. Icon for signifying phone calls would be awesome.

**Comment by ShimiSun** [comment]
Any of these one works?

![screen shot 2018-11-28 at 12 22 39 pm](https://user-images.githubusercontent.com/6320236/49176612-67b4f300-f308-11e8-87db-c2dc7dadb381.png)

**Comment by ShimiSun** [comment]
Or one of these

![screen shot 2018-11-28 at 12 48 55 pm](https://user-images.githubusercontent.com/6320236/49178080-10188680-f30c-11e8-99a6-7cfd660d8227.png)

**Comment by ShimiSun** [comment]
![screen shot 2018-11-28 at 12 50 47 pm](https://user-images.githubusercontent.com/6320236/49178178-4eae4100-f30c-11e8-8420-2b41187d7d75.png)

**Comment by tjackadams** [comment]
Hi @ShimiSun,

I can't speak for @obfuscatedgeek  but would it be possible just to have a normal phone icon such as 

![image](https://user-images.githubusercontent.com/2307314/49327990-bbba1480-f560-11e8-837b-f6d49725a592.png)

taken from https://material.io/tools/icons/?search=phone&style=baseline

**Comment by ShimiSun** [comment]
@L0ZZI ⬆️

**Comment by dgennetten** [comment]
@lozzi, if you good with this, pull me in and back up to speed on the process for adding a new icon. I can take this on going forward if you like.

**Comment by L0ZZI** [comment]
PR pending, https://github.com/grommet/grommet-icons/pull/91

**Comment by L0ZZI** [comment]
https://icons.grommet.io/?s=phone
