### ISSUE TITLE
Icon source in React

### ISSUE THREAD

**Issue by smooJitter** [grommet/grommet-icons#48]
I’m using react-native-vector icon.   Is there a way to acces the icon source instead of calling icon components?

**Comment by ShimiSun** [comment]
Hi @smooJitter, sorry for the late response here, can you please elaborate a little more in case the issue still relevant?

**Comment by taysea** [comment]
@smooJitter You can reference the `img` path: `"grommet-icons/img/notification.svg"`.

Closing this as a stale issue, but feel free to reopen if it's still relevant.
