### ISSUE TITLE
OSRB - add licensing files to the release files

### ISSUE THREAD

**Issue by cherih** [grommet/grommet-icons#49]
For OSRB purposes, need to include the following files with each release:
- licenses.json
- src-with-dependencies.tgz

**Comment by ericsoderberghp** [comment]
This is something that HPE should capture and publish outside of npm.

**Comment by ShimiSun** [comment]
pretty sure we can close this one. @MikeWalrath, feel free to reopen if this is a valid requirement and we have the right content to publish.
