### ISSUE TITLE
Console Warning in latest release

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet-icons#50]
Warning: Failed context type: Icon: context type undefined is invalid; it must be a function, usually from theprop-typespackage, but received undefined.

    in Icon (created by Bitcoin)
    in Bitcoin
    in div (created by StyledBox)

**Comment by alansouzati** [comment]
im working on this now.

**Comment by alansouzati** [comment]
fixed. 0.16.0 released

https://github.com/grommet/grommet-icons/releases/tag/v0.16.0
