### ISSUE TITLE
CodePen doesn't work with v. 3.0.0

### ISSUE THREAD

**Issue by srockk** [grommet/grommet-icons#60]
If I inject grommet-icons v3.0.0, the codepen doesn't work.

**Comment by alansouzati** [comment]
what do you mean by that?

here is a codesandbox using grommet-icons v3.

https://codesandbox.io/s/n76n29o430

Do you have the link to the codepen? We are not actually using codepen internally anymore since it does not support the concept of modules.

**Comment by srockk** [comment]
Thank you for the response. When I tried to inject grommet-icons v3. the codesandbox didn't boot up. But now it's working for me. I'll close the issue.
