### ISSUE TITLE
"export 'ThemeContext' (imported as 'IconThemeContext') was not found in 'grommet-icons'

### ISSUE THREAD

**Issue by nomadus** [grommet/grommet-icons#63]
After I installed grommet-icons and tried to use Spinning icon it gave me the following error. What has to be added?

./node_modules/grommet-controls/node_modules/grommet/es6/components/Grommet/Grommet.js
112:8-24 "export 'ThemeContext' (imported as 'IconThemeContext') was not found in 'grommet-icons'

**Comment by nomadus** [comment]
This probably not relevant issue, should be opened against grommet-controls

**Comment by atanasster** [comment]
@nomadus, you need to install the latest beta version of grommet-icons, the exports have been changing recently

**Comment by nomadus** [comment]
Thanks, I have another project where it works with the following packages
    "grommet": "^1.10.1",
    "grommet-addons": "^0.6.0",
    "grommet-controls": "^0.26.3",
    "grommet-icons": "^0.14.0",

Where could I get the beta version?

**Comment by atanasster** [comment]
very strange - i have not tried grommet-controls with grommet version 1 - its intended for use with grommet 2. And recently grommet 2 and grommet-icons have undergone serious refactoring to account for tree-shaking. 
The beta is `grommet-icons@3.1.0-beta.1`

What I am using in my projects is:

```
    "grommet": "https://github.com/grommet/grommet/tarball/NEXT-stable",
    "grommet-controls": "^0.46.15",
    "grommet-icons": "^3.1.0-beta.1",
```
