### ISSUE TITLE
React typescript project with Grommet v2 causes grommet-icons to not treeshake

### ISSUE THREAD

**Issue by dmcclurealinta** [grommet/grommet-icons#69]
**Issue:**
Typescript React project with Grommet 2.0 doesn't treeshake grommet-icons, causing the package to be 70% taken up with grommet-icons. 

**Built with:**
Webpack 4x

**Replicate:**
CRA with typescript, add grommet + grommet-icons(peer-dep), import any component like `import { Grid } from 'grommet/components/Grid';` run a build and then inspect the minified bundle with source-map-explorer, you will see that the makeup of the package is mostly grommet-icons.

**Comment by alansouzati** [comment]
are you declaring modules false in your babel config?

**Comment by alansouzati** [comment]
Yeah I just tried this in a repo. I was doing `import { grommet } from "grommet/themes"`, this is the culprit when doing Webpack 4 tree shaking. We are manually specifying we want the CommonJS distribution.

I've changed `import { grommet } from "grommet/themes"` to `import { grommet } from "grommet/es6/themes"` and it works fine after that.

Another possible option is to do like follows:

`import { grommet, Grommet, Box } from "grommet";`

basically avoid using the forward slash.

Yet another option is to use [babel-plugin-transform-imports](https://www.npmjs.com/package/babel-plugin-transform-imports)

Where the config would be something like this:

```
{
    "plugins": [
        ["transform-imports", {
            "grommet/themes$": {
                "transform": "grommet/es6/themes/${member}",
                "preventFullImport": true,
                "skipDefaultConversion":  true
            }
        }]
    ]
}
```

We should probably create a blog post about this. Getting tree shaking right can be a pain 😢

**Comment by dmcclurealinta** [comment]
import { grommet } from "grommet/themes" relates to grommet v1, in this instance I'm not bothering with that. I'll double check against babel-plugin-transform-imports to see if it will treeshake, but the ts compiler might be interfering with that also. I'll report back here when I complete.

**Comment by alansouzati** [comment]
> import { grommet } from "grommet/themes" relates to grommet v1

I dont think so.
