### ISSUE TITLE
Search Function on Landing Page Does Not Work

### ISSUE THREAD

**Issue by alexlee-dev** [grommet/grommet-icons#72]
I believe the state is being reset when the header at the top refreshes. Try searching for Group, and it doesn't give you group. But search for User and it gives you Group.

**Comment by ericsoderberghp** [comment]
Thanks for reporting this. I think this is probably an issue for https://github.com/grommet/grommet-icons-site.

**Comment by alexlee-dev** [comment]
Shoot, you're right. Thanks. I'll close this and open another one one that repo.
