### ISSUE TITLE
Apple Store and Google Play icons

### ISSUE THREAD

**Issue by nomadus** [grommet/grommet-icons#84]
Please add Apple Store and Google Play icons as they are missing

**Comment by ShimiSun** [comment]
asked Greg to help out

**Comment by gregfuruiye** [comment]
sent out an email request to the design team

**Comment by L0ZZI** [comment]
https://github.com/grommet/grommet-icons/pull/89

**Comment by ShimiSun** [comment]
@L0ZZI thanks! @gregfuruiye FYI.
