### ISSUE TITLE
Export a basic Icon in grommet-icons v4

### ISSUE THREAD

**Issue by srallen** [grommet/grommet-icons#87]
Note: initially posted: https://github.com/grommet/grommet/issues/2689

Expected Behavior
v1 of Grommet provided a base generic Icon component, then when the grommet-icons package was extracted out, it was still available there, although undocumented. The base Icon component is useful for any custom SVG logos an app might have, like a brand logo, but still making sure it inherits the Grommet theme colors and sizes. An exported, documented basic Icon in v4 and later versions will still be useful.

Actual Behavior
Icon is no longer available. StyledIcon can be used as a workaround, but it isn't a part of the rest of the exports and you must use the direct file path for it.

URL, screen shot, or Codepen exhibiting the issue
Steps to Reproduce
Try to use import { Icon } from 'grommet-icons'; It will break because Icon is no longer exported in v4.
Your Environment
Grommet version: 3.2.1 vs 4.1.0 of grommet-icons
Browser Name and version:
Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
Did you try using `Blank`?

**Comment by srallen** [comment]
No, I was unaware of `Blank`. Trying it now, this looks like it works for what I was trying to accomplish. Is this something that will be documented and supported in future versions?

**Comment by ShimiSun** [comment]
Yes, and feel free to make a contribution

**Comment by flaurida** [comment]
Quick question - how do I pass the svg path to `Blank`? Excited to try this out!

**Comment by srallen** [comment]
Any SVG element can be a child of `Blank`:
```
    <Blank
      viewBox='0 0 24 24'
      {...props}
    >
      <path d='' />
    </Blank>
```

**Comment by taysea** [comment]
Closing since `Blank` is documented in README: https://github.com/grommet/grommet-icons#create-your-own-grommet-icon
