### ISSUE TITLE
Grommet Icon Site couldn't filter the icon I want

### ISSUE THREAD

**Issue by jasonchuah4** [grommet/grommet-icons#88]
The site [https://grommet.github.io/grommet-icons/](https://grommet.github.io/grommet-icons/) couldn't filter out the icon I am looking for. I typed the keyword in the search bar but there is no respond from the browser.

Browser tested: Chrome, Edge
OS: Windows 10

**Comment by ShimiSun** [comment]
@jasonchuah4 Please use this site: https://icons.grommet.io/
It works for me.

Feel free to let me know where you found this link so we can fix the path.

**Comment by jasonchuah4** [comment]
@ShimiSun sorry for the late reply. The wrong link is inside this git repository README.MD [https://github.com/grommet/grommet-icons#usage](https://github.com/grommet/grommet-icons#usage), on the line of "Visit our _site_ for more icons."

**Comment by ShimiSun** [comment]
@jasonchuah4 good catch! it is fixed, thanks for the info.
