### ISSUE TITLE
Coffee bean icon? ☕

### ISSUE THREAD

**Issue by robinmetral** [grommet/grommet-icons#99]
I know this is typically not an icon that's included in sets, but I thought I'd simply ask: 

I'm looking for something like [this](https://thenounproject.com/icon/1886493/), but with more of a grommet-icons-y feel to it :slightly_smiling_face: 

Could this be added to the set?

**Comment by L0ZZI** [comment]
Sure. Fun diversion! Slanted or straight up?

![coffee](https://user-images.githubusercontent.com/1753301/54230155-13064400-44c3-11e9-9a31-b96b02f7fce6.png)
![coffee-slanted](https://user-images.githubusercontent.com/1753301/54230157-13064400-44c3-11e9-8f70-928f495a4f7f.png)
[coffee.svg.zip](https://github.com/grommet/grommet-icons/files/2958471/coffee.svg.zip)

**Comment by ShimiSun** [comment]
I like the Slanted :) @robinmetral what do you think?

**Comment by robinmetral** [comment]
Same here @ShimiSun, @L0ZZI it's amazing, thank you!

**Comment by oorestisime** [comment]
Closing this since it was merged
